server.port=8082
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
# Initialisation des données via Java (DataInitializer.java) plutôt que SQL
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:init-data.sql
# Désactive la génération du mot de passe de sécurité par défaut
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.web=DEBUG
logging.level.com.example.recruitment=DEBUG
# Pour voir les erreurs d'initialisation SQL détaillées
logging.level.org.springframework.jdbc.datasource.init=DEBUG